### ISSUE TITLE
No Viz Filtering in Experience Cloud

### ISSUE THREAD

**Issue by bogandev** [tableau/tableau-viz-lwc#119]
### Summary

Investigating for use in Experience Cloud: Fail
Goal: have a dashboard on a custom object and filter it based on a field on that custom object.
Problem: The filter option does not show in the Tableau Viz LWC configuration when it is on a Record Detail page (or custom Object Detail page) in Experience Cloud. Basically, the filter capability is deactivated in Experience Cloud. It works in Sales Cloud. Please activate this feature so we can use it in Experience Cloud.

### Steps To Reproduce:

1. Create an Experience
2. Add a custom object in the Nav menu
3. Add the component to the Record Detail page
4. Click on the component to enable filtering

### Expected result

The three menu options for filtering should be displayed in the component configuration.
![image](https://user-images.githubusercontent.com/99040801/152576152-5c520621-16b2-466c-973b-593df4688300.png)

### Actual result
Filter menu options are not displayed
![image](https://user-images.githubusercontent.com/99040801/152575961-4fce48e0-2524-4659-a95b-810202e1078f.png)

### Additional information

The happens on the OOTB Record Detail page and when you create a new Object page. Please update the settings so that the filter capability is available in Experience Cloud.

**Comment by TimFroger** [comment]
Hi,

As a workaround, could it be possible to include the parameters in the URL?

Such as https://tableau.com/views/Dashboard/1_DashboardName**?:AccountName={!CurrentUser.Name}**

**Comment by evande0** [comment]
# Tableau Viz LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau View LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm). 

For more information, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

--- 

**Re: The new Tableau View LWC**

@bogandev Unfortunately, this dynamic filtering functionality is only available on Record Pages. This is because the component knows what the current Record page is and can access fields for that Record. Experience Cloud doesn't support this kind of dynamic filtering. If you are interested in static filtering, you can use Custom Query Parameters in Experience Cloud instead.
