### ISSUE TITLE
Dashboard Selection for End Users

### ISSUE THREAD

**Issue by takashibinns** [tableau/tableau-viz-lwc#46]
**What is missing from the application? Please describe.**
The current state makes it easy for some salesforce users to paste in the URL for a dashboard, but not every user has permissions to edit lightning pages.  The customer would prefer if there was a mechanism for any user to switch which dashboard to view.

**Describe the solution you'd like**
A search box and/or dashboard selector menu, that uses the REST API to query the Tableau Server for available dashboards and allows any end user to select a different dashboard.  This should include setting a _default_ dashboard for the logged-in user.

**Describe alternatives you've considered**
For this customer, the end users do not have the ability to edit lightning pages.  So the work-around is that IT can create multiple tabs on the page and each one would have the LWC pointed to a different dashboard.  This is a bit more annoying to manage, but does provide the access they desire.

**Additional context**
N/A

**Comment by evande0** [comment]
# Tableau _Viz_ LWC is being Archived

All outstanding PRs and Issues are being addressed and closed. Please migrate to the new [Tableau **_View_** LWC](https://help.tableau.com/current/online/en-us/lwc_seamless_auth.htm).

For more information about why the Tableau **Viz** LWC is being replaced by the Tableau **View** LWC, please see the [README](https://github.com/tableau/tableau-viz-lwc?tab=readme-ov-file#archived-tableau-viz-lwc-is-being-replaced-by-native-tableau-view-lwc)

---

@takashibinns I think the tabbed approach is probably the best solution we can offer since no new features are planned for the Tableau View LWC. If you have other ideas, feel free to reach out on the internal Eureka channel or file a Team Dependency. Thanks!
